name: presage
channels:
- bioconda
- conda-forge
- nvidia
- pyg
- pytorch
dependencies:
- aiohappyeyeballs
- aiohttp
- aiosignal
- alembic
- anndata
- annotated-types
- anyio
- appdirs
- argon2-cffi
- argon2-cffi-bindings
- arpack
- array-api-compat
- arrow
- asttokens
- async-lru
- attrs
- aws-c-auth
- aws-c-cal
- aws-c-common
- aws-c-compression
- aws-c-event-stream
- aws-c-http
- aws-c-io
- aws-c-mqtt
- aws-c-s3
- aws-c-sdkutils
- aws-checksums
- aws-crt-cpp
- aws-sdk-cpp
- azure-core-cpp
- azure-identity-cpp
- azure-storage-blobs-cpp
- azure-storage-common-cpp
- azure-storage-files-datalake-cpp
- babel
- beautifulsoup4
- bleach
- bleach-with-css
- brotli
- brotli-bin
- brotli-python
- bzip2
- c-ares
- ca-certificates
- cached-property
- cached_property
- certifi
- cffi
- charset-normalizer
- click
- cloudpickle
- colorama
- colorlog
- comm
- contourpy
- cpython
- cycler
- cytoolz
- dask-core
- dcor
- debugpy
- decorator
- defusedxml
- distributed
- docker-pycreds
- eval_type_backport
- exceptiongroup
- executing
- filelock
- fonttools
- fqdn
- freetype
- frozenlist
- fsspec
- gflags
- gitdb
- gitpython
- glog
- glpk
- gmp
- gmpy2
- greenlet
- h11
- h2
- h5py
- harmonypy
- hdf5
- hpack
- httpcore
- httpx
- hyperframe
- icu
- idna
- igraph
- importlib-metadata
- importlib_resources
- ipykernel
- ipython
- ipython_pygments_lexers
- isoduration
- jedi
- jinja2
- joblib
- json5
- jsonpointer
- jsonschema
- jsonschema-specifications
- jsonschema-with-format-nongpl
- jupyter-lsp
- jupyter_client
- jupyter_core
- jupyter_events
- jupyter_server
- jupyter_server_terminals
- jupyterlab
- jupyterlab_pygments
- jupyterlab_server
- jupyterthemes
- kiwisolver
- krb5
- lcms2
- ld_impl_linux-64
- legacy-api-wrap
- leidenalg
- lerc
- lesscpy
- libabseil
- libaec
- libarrow
- libarrow-acero
- libarrow-dataset
- libarrow-substrait
- libblas
- libbrotlicommon
- libbrotlidec
- libbrotlienc
- libcblas
- libcrc32c
- libcurl
- libdeflate
- libedit
- libev
- libevent
- libexpat
- libffi
- libfreetype
- libfreetype6
- libgfortran
- libgfortran5
- libgoogle-cloud
- libgoogle-cloud-storage
- libgrpc
- libhwloc
- libiconv
- libjpeg-turbo
- liblapack
- libleidenalg
- liblzma
- libnghttp2
- libopentelemetry-cpp
- libopentelemetry-cpp-headers
- libparquet
- libpng
- libprotobuf
- libre2-11
- libsodium
- libsqlite
- libssh2
- libthrift
- libtiff
- libutf8proc
- libuuid
- libwebp-base
- libxcb
- libxcrypt
- libxml2
- libzlib
- lightning-utilities
- llvm-openmp
- llvmlite
- locket
- lz4-c
- mako
- markupsafe
- matplotlib-base
- matplotlib-inline
- mistune
- mpc
- mpfr
- mpmath
- msgpack-python
- multidict
- munkres
- natsort
- nbclient
- nbconvert-core
- nbformat
- ncurses
- nest-asyncio
- networkx
- nlohmann_json
- notebook
- notebook-shim
- numba
- numpy
- openjpeg
- openssl
- optuna
- optuna-integration
- orc
- overrides
- packaging
- pandas
- pandocfilters
- parso
- partd
- patsy
- pexpect
- pickleshare
- pillow
- pip
- pkgutil-resolve-name
- platformdirs
- ply
- prometheus-cpp
- prometheus_client
- prompt-toolkit
- propcache
- protobuf
- psutil
- pthread-stubs
- ptyprocess
- pure_eval
- pyarrow
- pyarrow-core
- pycparser
- pydantic
- pydantic-core
- pyg
- pygments
- pynndescent
- pyparsing
- pysocks
- python
- python-dateutil
- python-fastjsonschema
- python-igraph
- python-json-logger
- python-tzdata
- python_abi
- pytorch
- pytorch-cluster
- pytorch-lightning
- pytorch-mutex
- pytz
- pyyaml
- pyzmq
- qhull
- re2
- readline
- referencing
- requests
- rfc3339-validator
- rfc3986-validator
- rpds-py
- s2n
- scanpy
- scikit-learn
- scipy
- seaborn
- seaborn-base
- send2trash
- sentry-sdk
- session-info
- setproctitle
- setuptools
- six
- smmap
- snappy
- sniffio
- sortedcontainers
- soupsieve
- sqlalchemy
- stack_data
- statsmodels
- stdlib-list
- sympy
- tbb
- tblib
- terminado
- texttable
- threadpoolctl
- tinycss2
- tk
- tomli
- toolz
- torchmetrics
- tornado
- tqdm
- traitlets
- types-python-dateutil
- typing
- typing-extensions
- typing-inspection
- typing_extensions
- typing_utils
- tzdata
- umap-learn
- unicodedata2
- uri-template
- urllib3
- wandb
- wcwidth
- webcolors
- webencodings
- websocket-client
- wheel
- xorg-libxau
- xorg-libxdmcp
- yaml
- yarl
- zeromq
- zict
- zipp
- zlib
- zstandard
- zstd